fab publish_test:iris_local_test
fab publish_test:mortality_prediction_local_test
fab publish_test:pollenating_insects_local_test
fab publish_test:kaggle_otto_local_test

cd /tmp/databoard_local/databoard_iris_8080
fab test_ramp
cd /tmp/databoard_local/databoard_mortality_prediction_8080
fab test_ramp
cd /tmp/databoard_local/databoard_pollenating_insects_8080
fab test_ramp
cd /tmp/databoard_local/databoard_kaggle_otto_8080
fab test_ramp
