version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.4
        environment:
            # miniconda path install
            MINICONDA_PATH: ~/miniconda
      - image: circleci/postgres:9.6.2
        environment:
            POSTGRES_USER: mrramp
            POSTGRES_PASSWORD: mrramp
            POSTGRES_DB: databoard_test
    environment:
      # The github organization or username of the repository which hosts the
      # project and documentation.
      USERNAME: glemaitre
      # The name of the organization which host the repositories
      ORGANIZATION: paris-saclay-cds
      # The repository where the documentation will be hosted
      DOC_REPO: ramp-docs
      # The branch of the documentation
      DOC_BRANCH: master
      # The base URL for the Github page where the documentation will be hosted
      DOC_URL: ""
      # The email is to be used for commits in the Github Page
      EMAIL: g.lemaitre58@gmail.com
    steps:
      - checkout
      - run:
          name: Checkout merge commit
          command: ./ci_tools/circle/checkout_merge_commit.sh
      - run:
          # Check whether the doc build is required, install build dependencies and
          # run sphinx to build the doc.
          name: Build documentation
          command: ./ci_tools/circle/build_doc.sh
          timeout: "3600"  # seconds

      - run:
          # Grep error on the documentation
          name: Parse errors
          command: cat ~/log.txt && if grep -q "Traceback (most recent call last):" ~/log.txt; then false; else true; fi

      - store_artifacts:
          name: Store the log
          path: ~/log.txt
      - store_artifacts:
          name: Store the documentation
          path: doc/_build/html/stable

      - add_ssh_keys:
          fingerprints:
              - "09:57:56:6e:0b:ad:45:11:83:08:e4:72:d4:78:77:18"

      - deploy:
          name: Deploy documentation
          command: ./ci_tools/circle/push_doc.sh doc/_build/html/stable
