"""drop submission_file name

Revision ID: 23ccd9090bf
Revises: 55206be47b71
Create Date: 2015-12-09 23:02:08.683977

"""

# revision identifiers, used by Alembic.
revision = '23ccd9090bf'
down_revision = '55206be47b71'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.drop_column('submission_files', 'name')


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ts_constraint', 'submissions', type_='unique')
    op.drop_constraint('sc_constraint', 'submission_on_cv_folds', type_='unique')
    op.add_column('submission_files', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_constraint(None, 'submission_files', type_='foreignkey')
    op.alter_column('submission_files', 'file_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###
