"""empty message

Revision ID: 19f2e902b5ce
Revises: 3dc6081d9375
Create Date: 2017-06-05 21:00:08.995009

"""

# revision identifiers, used by Alembic.
revision = '19f2e902b5ce'
down_revision = '3dc6081d9375'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('problem_keywords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('data_domain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_domain_id'], ['keywords.id'], ),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('problem_keywords')
    op.drop_table('keywords')
    ### end Alembic commands ###
