"""empty message

Revision ID: 36121d772f13
Revises: 60f4ddecbb5f
Create Date: 2016-12-22 16:53:24.637539

"""

# revision identifiers, used by Alembic.
revision = '36121d772f13'
down_revision = '60f4ddecbb5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_contributivitys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('contributivity', sa.Float(), nullable=True),
    sa.Column('historical_contributivity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historical_contributivitys')
    ### end Alembic commands ###
