"""empty message

Revision ID: 3dc6081d9375
Revises: b7ea6f6aa685
Create Date: 2017-06-04 19:42:33.000664

"""

# revision identifiers, used by Alembic.
revision = '3dc6081d9375'
down_revision = 'b7ea6f6aa685'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('n_submissions', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'n_submissions')
    ### end Alembic commands ###
