"""empty message

Revision ID: 4211b7c3e1e8
Revises: 36121d772f13
Create Date: 2016-12-31 20:13:04.936361

"""

# revision identifiers, used by Alembic.
revision = '4211b7c3e1e8'
down_revision = '36121d772f13'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_teams', sa.Column('failed_leaderboard_html', sa.String(), nullable=True))
    op.add_column('event_teams', sa.Column('leaderboard_html', sa.String(), nullable=True))
    op.add_column('event_teams', sa.Column('new_leaderboard_html', sa.String(), nullable=True))
    op.add_column('events', sa.Column('failed_leaderboard_html', sa.String(), nullable=True))
    op.add_column('events', sa.Column('new_leaderboard_html', sa.String(), nullable=True))
    op.add_column('events', sa.Column('private_leaderboard_html', sa.String(), nullable=True))
    op.add_column('events', sa.Column('public_leaderboard_html_no_links', sa.String(), nullable=True))
    op.add_column('events', sa.Column('public_leaderboard_html_with_links', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'public_leaderboard_html_with_links')
    op.drop_column('events', 'public_leaderboard_html_no_links')
    op.drop_column('events', 'private_leaderboard_html')
    op.drop_column('events', 'new_leaderboard_html')
    op.drop_column('events', 'failed_leaderboard_html')
    op.drop_column('event_teams', 'new_leaderboard_html')
    op.drop_column('event_teams', 'leaderboard_html')
    op.drop_column('event_teams', 'failed_leaderboard_html')
    ### end Alembic commands ###
