"""empty message

Revision ID: 60f4ddecbb5f
Revises: f151d8d44b84
Create Date: 2016-11-29 11:09:59.982619

"""

# revision identifiers, used by Alembic.
revision = '60f4ddecbb5f'
down_revision = 'f151d8d44b84'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_teams', sa.Column('approved', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_teams', 'approved')
    ### end Alembic commands ###
