"""empty message

Revision ID: 68f8b62efa49
Revises: 8e12dbac1032
Create Date: 2016-06-29 10:23:16.012209

"""

# revision identifiers, used by Alembic.
revision = '68f8b62efa49'
down_revision = '8e12dbac1032'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('official_score_name', sa.String(), nullable=True))
    op.drop_column('events', 'official_score_index')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('official_score_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('events', 'official_score_name')
    ### end Alembic commands ###
