"""empty message

Revision ID: 71bd40617373
Revises: aa057100f878
Create Date: 2018-05-23 11:44:29.981088

"""

# revision identifiers, used by Alembic.
revision = '71bd40617373'
down_revision = 'aa057100f878'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('private_competition_leaderboard_html', sa.String(), nullable=True))
    op.add_column('events', sa.Column('public_competition_leaderboard_html', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'public_competition_leaderboard_html')
    op.drop_column('events', 'private_competition_leaderboard_html')
    # ### end Alembic commands ###
