"""empty message

Revision ID: 73dd0fddab62
Revises: 98d8c068c768
Create Date: 2016-07-06 08:49:02.626795

"""

# revision identifiers, used by Alembic.
revision = '73dd0fddab62'
down_revision = '98d8c068c768'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('official_score_name', sa.String(), nullable=True))
    op.drop_column('events', 'official_score_index')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('official_score_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('events', 'official_score_name')
    ### end Alembic commands ###
