"""empty message

Revision ID: 8e12dbac1032
Revises: 6e6b36cfa2a7
Create Date: 2016-06-29 09:58:55.687520

"""

# revision identifiers, used by Alembic.
revision = '8e12dbac1032'
down_revision = '6e6b36cfa2a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('official_score_index', sa.Integer(), nullable=True))
    op.drop_column('events', 'official_score_name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('official_score_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('events', 'official_score_index')
    ### end Alembic commands ###
