"""empty message

Revision ID: aa057100f878
Revises: b781be9c6150
Create Date: 2018-05-06 14:20:00.191738

"""

# revision identifiers, used by Alembic.
revision = 'aa057100f878'
down_revision = 'b781be9c6150'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('is_competitive', sa.Boolean(), nullable=True))
    op.add_column('submissions', sa.Column('is_in_competition', sa.Boolean(), nullable=True))
    op.add_column('submissions', sa.Column('max_ram', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'max_ram')
    op.drop_column('submissions', 'is_in_competition')
    op.drop_column('events', 'is_competitive')
    # ### end Alembic commands ###
