"""empty message

Revision ID: b00d69bcda81
Revises: 19f2e902b5ce
Create Date: 2017-06-05 21:24:57.536411

"""

# revision identifiers, used by Alembic.
revision = 'b00d69bcda81'
down_revision = '19f2e902b5ce'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_keywords', sa.Column('keyword_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'problem_keywords_data_domain_id_fkey', 'problem_keywords', type_='foreignkey')
    op.create_foreign_key(None, 'problem_keywords', 'keywords', ['keyword_id'], ['id'])
    op.drop_column('problem_keywords', 'data_domain_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('problem_keywords', sa.Column('data_domain_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'problem_keywords', type_='foreignkey')
    op.create_foreign_key(u'problem_keywords_data_domain_id_fkey', 'problem_keywords', 'keywords', ['data_domain_id'], ['id'])
    op.drop_column('problem_keywords', 'keyword_id')
    ### end Alembic commands ###
