"""Adding new submission states `scored` and `sent_to_training` and
`Submission.sent_to_training_timestamp` to handle backend server hangs.

Revision ID: b781be9c6150
Revises: d2089df73116
Create Date: 2017-09-21 16:08:11.428401

"""

# revision identifiers, used by Alembic.
revision = 'b781be9c6150'
down_revision = 'd2089df73116'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('sent_to_training_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'sent_to_training_timestamp')
    # ### end Alembic commands ###
