"""empty message

Revision ID: b7ea6f6aa685
Revises: manual2
Create Date: 2017-05-07 09:55:23.306243

"""

# revision identifiers, used by Alembic.
revision = 'b7ea6f6aa685'
down_revision = 'manual2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_interactions', sa.Column('problem_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_interactions', 'problems', ['problem_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_interactions', type_='foreignkey')
    op.drop_column('user_interactions', 'problem_id')
    ### end Alembic commands ###
