"""empty message

Revision ID: e80a353ef8b5
Revises: None
Create Date: 2016-06-28 09:47:48.417381

"""

# revision identifiers, used by Alembic.
revision = 'e80a353ef8b5'
down_revision = None

from alembic import op
import sqlalchemy as sa
import databoard

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('en_constraint', 'event_score_types', ['event_id', 'name'])
    op.add_column('events', sa.Column('official_score_name', sa.String(), nullable=True))
    op.drop_column('events', 'official_score_index')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('official_score_index', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('events', 'official_score_name')
    op.drop_constraint('en_constraint', 'event_score_types', type_='unique')
    ### end Alembic commands ###
